// <auto-generated />
using System;
using EduTrail.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduTrail.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316185608_initial-migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduTrail.Domain.Entities.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableCredit")
                        .HasColumnType("int");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OpenDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseOfferingId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.AutoGenerateNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AutoGenerateNumbers");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Institute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.CourseOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("TermId");

                    b.ToTable("CourseOfferings");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EnrolledDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TotalWorkHoursPerWeek")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Lab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.LabRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedTeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IssueDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("RequestedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TrySofar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ZoomLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTeacherId");

                    b.HasIndex("CourseOfferingId");

                    b.HasIndex("StatusId");

                    b.HasIndex("StudentId");

                    b.ToTable("LabRequests");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_BLOB_TRIGGER", b =>
                {
                    b.Property<string>("SCHED_NAME")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TRIGGER_NAME")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TRIGGER_GROUP")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("BLOB_DATA")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

                    b.ToTable("QURTZ_BLOB_TRIGGERS");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_CALENDAR", b =>
                {
                    b.Property<string>("SCHED_NAME")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CALENDAR_NAME")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("CALENDAR")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("SCHED_NAME", "CALENDAR_NAME");

                    b.ToTable("QURTZ_CALENDARS");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_CRON_TRIGGER", b =>
                {
                    b.Property<string>("SCHED_NAME")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TRIGGER_NAME")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TRIGGER_GROUP")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CRON_EXPRESSION")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TIME_ZONE_ID")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

                    b.ToTable("QURTZ_CRON_TRIGGERS");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_FIRED_TRIGGER", b =>
                {
                    b.Property<string>("SCHED_NAME")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ENTRY_ID")
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<long>("FIRED_TIME")
                        .HasColumnType("bigint");

                    b.Property<string>("INSTANCE_NAME")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IS_NONCONCURRENT")
                        .HasColumnType("bit");

                    b.Property<string>("JOB_GROUP")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("JOB_NAME")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PRIORITY")
                        .HasColumnType("int");

                    b.Property<bool?>("REQUESTS_RECOVERY")
                        .HasColumnType("bit");

                    b.Property<long>("SCHED_TIME")
                        .HasColumnType("bigint");

                    b.Property<string>("STATE")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TRIGGER_GROUP")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TRIGGER_NAME")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SCHED_NAME", "ENTRY_ID");

                    b.HasIndex(new[] { "SCHED_NAME", "JOB_GROUP", "JOB_NAME" }, "IDX_QRTZ_FT_G_J");

                    b.HasIndex(new[] { "SCHED_NAME", "TRIGGER_GROUP", "TRIGGER_NAME" }, "IDX_QRTZ_FT_G_T");

                    b.HasIndex(new[] { "SCHED_NAME", "INSTANCE_NAME", "REQUESTS_RECOVERY" }, "IDX_QRTZ_FT_INST_JOB_REQ_RCVRY");

                    b.ToTable("QURTZ_FIRED_TRIGGERS");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_JOB_DETAIL", b =>
                {
                    b.Property<string>("SCHED_NAME")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("JOB_NAME")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("JOB_GROUP")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DESCRIPTION")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IS_DURABLE")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_NONCONCURRENT")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_UPDATE_DATA")
                        .HasColumnType("bit");

                    b.Property<string>("JOB_CLASS_NAME")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("JOB_DATA")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("REQUESTS_RECOVERY")
                        .HasColumnType("bit");

                    b.HasKey("SCHED_NAME", "JOB_NAME", "JOB_GROUP");

                    b.ToTable("QURTZ_JOB_DETAILS");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_LOCK", b =>
                {
                    b.Property<string>("SCHED_NAME")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LOCK_NAME")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("SCHED_NAME", "LOCK_NAME");

                    b.ToTable("QURTZ_LOCKS");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_PAUSED_TRIGGER_GRP", b =>
                {
                    b.Property<string>("SCHED_NAME")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TRIGGER_GROUP")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SCHED_NAME", "TRIGGER_GROUP");

                    b.ToTable("QURTZ_PAUSED_TRIGGER_GRPS");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_SCHEDULER_STATE", b =>
                {
                    b.Property<string>("SCHED_NAME")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("INSTANCE_NAME")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("CHECKIN_INTERVAL")
                        .HasColumnType("bigint");

                    b.Property<long>("LAST_CHECKIN_TIME")
                        .HasColumnType("bigint");

                    b.HasKey("SCHED_NAME", "INSTANCE_NAME");

                    b.ToTable("QURTZ_SCHEDULER_STATE");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_SIMPLE_TRIGGER", b =>
                {
                    b.Property<string>("SCHED_NAME")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TRIGGER_NAME")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TRIGGER_GROUP")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("REPEAT_COUNT")
                        .HasColumnType("int");

                    b.Property<long>("REPEAT_INTERVAL")
                        .HasColumnType("bigint");

                    b.Property<int>("TIMES_TRIGGERED")
                        .HasColumnType("int");

                    b.HasKey("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

                    b.ToTable("QURTZ_SIMPLE_TRIGGERS");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_SIMPROP_TRIGGER", b =>
                {
                    b.Property<string>("SCHED_NAME")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TRIGGER_NAME")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TRIGGER_GROUP")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("BOOL_PROP_1")
                        .HasColumnType("bit");

                    b.Property<bool?>("BOOL_PROP_2")
                        .HasColumnType("bit");

                    b.Property<decimal?>("DEC_PROP_1")
                        .HasColumnType("numeric(13, 4)");

                    b.Property<decimal?>("DEC_PROP_2")
                        .HasColumnType("numeric(13, 4)");

                    b.Property<int?>("INT_PROP_1")
                        .HasColumnType("int");

                    b.Property<int?>("INT_PROP_2")
                        .HasColumnType("int");

                    b.Property<long?>("LONG_PROP_1")
                        .HasColumnType("bigint");

                    b.Property<long?>("LONG_PROP_2")
                        .HasColumnType("bigint");

                    b.Property<string>("STR_PROP_1")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("STR_PROP_2")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("STR_PROP_3")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TIME_ZONE_ID")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

                    b.ToTable("QURTZ_SIMPROP_TRIGGERS");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_TRIGGER", b =>
                {
                    b.Property<string>("SCHED_NAME")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TRIGGER_NAME")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TRIGGER_GROUP")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CALENDAR_NAME")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DESCRIPTION")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("END_TIME")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("JOB_DATA")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("JOB_GROUP")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("JOB_NAME")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("MISFIRE_INSTR")
                        .HasColumnType("int");

                    b.Property<long?>("NEXT_FIRE_TIME")
                        .HasColumnType("bigint");

                    b.Property<long?>("PREV_FIRE_TIME")
                        .HasColumnType("bigint");

                    b.Property<int?>("PRIORITY")
                        .HasColumnType("int");

                    b.Property<long>("START_TIME")
                        .HasColumnType("bigint");

                    b.Property<string>("TRIGGER_STATE")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TRIGGER_TYPE")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP");

                    b.HasIndex("SCHED_NAME", "JOB_NAME", "JOB_GROUP");

                    b.HasIndex(new[] { "SCHED_NAME", "CALENDAR_NAME" }, "IDX_QRTZ_T_C");

                    b.HasIndex(new[] { "SCHED_NAME", "JOB_GROUP", "JOB_NAME" }, "IDX_QRTZ_T_G_J");

                    b.HasIndex(new[] { "SCHED_NAME", "NEXT_FIRE_TIME" }, "IDX_QRTZ_T_NEXT_FIRE_TIME");

                    b.HasIndex(new[] { "SCHED_NAME", "TRIGGER_STATE", "NEXT_FIRE_TIME" }, "IDX_QRTZ_T_NFT_ST");

                    b.HasIndex(new[] { "SCHED_NAME", "MISFIRE_INSTR", "NEXT_FIRE_TIME", "TRIGGER_STATE" }, "IDX_QRTZ_T_NFT_ST_MISFIRE");

                    b.HasIndex(new[] { "SCHED_NAME", "MISFIRE_INSTR", "NEXT_FIRE_TIME", "TRIGGER_GROUP", "TRIGGER_STATE" }, "IDX_QRTZ_T_NFT_ST_MISFIRE_GRP");

                    b.HasIndex(new[] { "SCHED_NAME", "TRIGGER_GROUP", "TRIGGER_STATE" }, "IDX_QRTZ_T_N_G_STATE");

                    b.HasIndex(new[] { "SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP", "TRIGGER_STATE" }, "IDX_QRTZ_T_N_STATE");

                    b.HasIndex(new[] { "SCHED_NAME", "TRIGGER_STATE" }, "IDX_QRTZ_T_STATE");

                    b.ToTable("QURTZ_TRIGGERS");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("MaxPoints")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OriginalValue")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.QuestionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswerJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrectScorePercentage")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GeneratedParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudentAnswerJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("QuestionAttempt");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.QuestionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrectOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsMovable")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("QuestionLines");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.QuestionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("QuestionTypes");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.QuestionVariantTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptScore")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionVariantTemplates");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.QuestionVariationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionVariationRules");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StatusTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.StatusType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("StatusTypes");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("QuestionAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudentAnswerJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("QuestionAttemptId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.TALabDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LabDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TALabWeekId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TALabWeekId");

                    b.ToTable("TALabDays");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.TALabMonth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("TALabMonths");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.TALabSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("RemoteLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("TALabDayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TALabDayId");

                    b.ToTable("TALabSlots");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.TALabWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TALabMonthId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TALabMonthId");

                    b.ToTable("TALabWeeks");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TermTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TermTypeId");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.TermType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("TermTypes");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EduTrail.Infrastructure.Data.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ChangedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangedProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Assessment", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrail.Domain.Entities.CourseOffering", null)
                        .WithMany("Assessments")
                        .HasForeignKey("CourseOfferingId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.CourseOffering", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.Course", "Course")
                        .WithMany("CourseOfferings")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrail.Domain.Entities.User", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId");

                    b.HasOne("EduTrail.Domain.Entities.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.CourseOffering", "CourseOffering")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrail.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CourseOffering");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Lab", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.CourseOffering", "CourseOffering")
                        .WithMany()
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseOffering");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.LabRequest", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.Enrollment", "AssignedTeacher")
                        .WithMany()
                        .HasForeignKey("AssignedTeacherId");

                    b.HasOne("EduTrail.Domain.Entities.CourseOffering", "CourseOffering")
                        .WithMany()
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrail.Domain.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrail.Domain.Entities.Enrollment", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTeacher");

                    b.Navigation("CourseOffering");

                    b.Navigation("Status");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_CRON_TRIGGER", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.Quartzs.QURTZ_TRIGGER", "QURTZ_TRIGGER")
                        .WithOne("QURTZ_CRON_TRIGGER")
                        .HasForeignKey("EduTrail.Domain.Entities.Quartzs.QURTZ_CRON_TRIGGER", "SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QURTZ_TRIGGER");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_SIMPLE_TRIGGER", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.Quartzs.QURTZ_TRIGGER", "QURTZ_TRIGGER")
                        .WithOne("QURTZ_SIMPLE_TRIGGER")
                        .HasForeignKey("EduTrail.Domain.Entities.Quartzs.QURTZ_SIMPLE_TRIGGER", "SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QURTZ_TRIGGER");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_SIMPROP_TRIGGER", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.Quartzs.QURTZ_TRIGGER", "QURTZ_TRIGGER")
                        .WithOne("QURTZ_SIMPROP_TRIGGER")
                        .HasForeignKey("EduTrail.Domain.Entities.Quartzs.QURTZ_SIMPROP_TRIGGER", "SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QURTZ_TRIGGER");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_TRIGGER", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.Quartzs.QURTZ_JOB_DETAIL", "QURTZ_JOB_DETAIL")
                        .WithMany("QURTZ_TRIGGERs")
                        .HasForeignKey("SCHED_NAME", "JOB_NAME", "JOB_GROUP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QURTZ_JOB_DETAIL");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Question", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.Assessment", "Assessment")
                        .WithMany("Questions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrail.Domain.Entities.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.QuestionVariantTemplate", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.Question", "Question")
                        .WithMany("VariantTemplates")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.QuestionVariationRule", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.Question", "Question")
                        .WithMany("VariationRules")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Status", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Submission", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.QuestionAttempt", "QuestionAttempt")
                        .WithMany()
                        .HasForeignKey("QuestionAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionAttempt");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.TALabDay", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.TALabWeek", "TALabWeek")
                        .WithMany("Days")
                        .HasForeignKey("TALabWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TALabWeek");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.TALabMonth", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany("TALabMonths")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.TALabSlot", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.TALabDay", "TALabDay")
                        .WithMany("Slots")
                        .HasForeignKey("TALabDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TALabDay");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.TALabWeek", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.TALabMonth", "TALabMonth")
                        .WithMany("Weeks")
                        .HasForeignKey("TALabMonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TALabMonth");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Term", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.TermType", "TermType")
                        .WithMany()
                        .HasForeignKey("TermTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TermType");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("EduTrail.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrail.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Assessment", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Course", b =>
                {
                    b.Navigation("CourseOfferings");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.CourseOffering", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Enrollment", b =>
                {
                    b.Navigation("TALabMonths");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_JOB_DETAIL", b =>
                {
                    b.Navigation("QURTZ_TRIGGERs");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Quartzs.QURTZ_TRIGGER", b =>
                {
                    b.Navigation("QURTZ_CRON_TRIGGER");

                    b.Navigation("QURTZ_SIMPLE_TRIGGER");

                    b.Navigation("QURTZ_SIMPROP_TRIGGER");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.Question", b =>
                {
                    b.Navigation("VariantTemplates");

                    b.Navigation("VariationRules");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.TALabDay", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.TALabMonth", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("EduTrail.Domain.Entities.TALabWeek", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
